apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: adoptapup
  labels:
    app: mongodb
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: registry.access.redhat.com/rhscl/mongodb-36-rhel7
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_USER
              value: "developer"
            - name: MONGODB_PASSWORD
              value: "developer"
            - name: MONGODB_DATABASE
              value: "adoptapup"
            - name: MONGODB_ADMIN_PASSWORD
              value: "redhat"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: adoptapup
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb
